window.kanjiList1 = [
{k:"一",en:"One",si:"එක",h:"いち",r:"ichi"},
{k:"二",en:"Two",si:"දෙක",h:"に",r:"ni"},
{k:"三",en:"Three",si:"තුන",h:"さん",r:"san"},
{k:"四",en:"Four",si:"හතර",h:"し",r:"shi"},
{k:"五",en:"Five",si:"පහ",h:"ご",r:"go"},
{k:"六",en:"Six",si:"හය",h:"ろく",r:"roku"},
{k:"七",en:"Seven",si:"හත",h:"しち",r:"shichi"},
{k:"八",en:"Eight",si:"අට",h:"はち",r:"hachi"},
{k:"九",en:"Nine",si:"නවය",h:"きゅう",r:"kyuu"},
{k:"十",en:"Ten",si:"දහය",h:"じゅう",r:"juu"},

{k:"百",en:"Hundred",si:"සියය",h:"ひゃく",r:"hyaku"},
{k:"千",en:"Thousand",si:"දහස",h:"せん",r:"sen"},
{k:"万",en:"Ten thousand",si:"දස දහස",h:"まん",r:"man"},
{k:"円",en:"Yen",si:"යෙන්",h:"えん",r:"en"},
{k:"日",en:"Day",si:"දවස",h:"にち",r:"nichi"},
{k:"月",en:"Month",si:"මාසය",h:"げつ",r:"getsu"},
{k:"火",en:"Fire",si:"ගින්න",h:"か",r:"ka"},
{k:"水",en:"Water",si:"ජලය",h:"すい",r:"sui"},
{k:"木",en:"Tree",si:"ගස",h:"もく",r:"moku"},
{k:"金",en:"Gold",si:"රත්තරන්",h:"きん",r:"kin"},

{k:"土",en:"Earth",si:"පස",h:"ど",r:"do"},
{k:"年",en:"Year",si:"අවුරුද්ද",h:"ねん",r:"nen"},
{k:"時",en:"Time",si:"වේලාව",h:"じ",r:"ji"},
{k:"分",en:"Minute",si:"විනාඩිය",h:"ふん",r:"fun"},
{k:"午",en:"Noon",si:"දහවල්",h:"ご",r:"go"},
{k:"前",en:"Before",si:"පෙර",h:"まえ",r:"mae"},
{k:"後",en:"After",si:"පසු",h:"あと",r:"ato"},
{k:"今",en:"Now",si:"දැන්",h:"いま",r:"ima"},
{k:"先",en:"Previous",si:"පෙර",h:"さき",r:"saki"},
{k:"半",en:"Half",si:"බාගය",h:"はん",r:"han"},

{k:"毎",en:"Every",si:"හැම",h:"まい",r:"mai"},
{k:"何",en:"What",si:"මොකක්ද",h:"なに",r:"nani"},
{k:"人",en:"Person",si:"මනුස්සයා",h:"ひと",r:"hito"},
{k:"男",en:"Man",si:"පිරිමි",h:"おとこ",r:"otoko"},
{k:"女",en:"Woman",si:"ගැහැණු",h:"おんな",r:"onna"},
{k:"子",en:"Child",si:"ළමයා",h:"こ",r:"ko"},
{k:"母",en:"Mother",si:"අම්මා",h:"はは",r:"haha"},
{k:"父",en:"Father",si:"තාත්තා",h:"ちち",r:"chichi"},
{k:"友",en:"Friend",si:"යාලුවා",h:"とも",r:"tomo"},
{k:"上",en:"Up",si:"උඩ",h:"うえ",r:"ue"},

{k:"下",en:"Down",si:"යට",h:"した",r:"shita"},
{k:"左",en:"Left",si:"වම",h:"ひだり",r:"hidari"},
{k:"右",en:"Right",si:"දකුණ",h:"みぎ",r:"migi"},
{k:"中",en:"Middle",si:"මැද",h:"なか",r:"naka"},
{k:"外",en:"Outside",si:"එළිය",h:"そと",r:"soto"},
{k:"東",en:"East",si:"නැගෙනහිර",h:"ひがし",r:"higashi"},
{k:"西",en:"West",si:"බටහිර",h:"にし",r:"nishi"},
{k:"南",en:"South",si:"දකුණ",h:"みなみ",r:"minami"},
{k:"北",en:"North",si:"උතුර",h:"きた",r:"kita"},
{k:"口",en:"Mouth",si:"කට",h:"くち",r:"kuchi"},

{k:"目",en:"Eye",si:"ඇස",h:"め",r:"me"},
{k:"耳",en:"Ear",si:"කන",h:"みみ",r:"mimi"},
{k:"手",en:"Hand",si:"අත",h:"て",r:"te"},
{k:"足",en:"Foot",si:"කකුල",h:"あし",r:"ashi"},
{k:"大",en:"Big",si:"ලොකු",h:"だい",r:"dai"},
{k:"小",en:"Small",si:"පොඩි",h:"しょう",r:"shou"},
{k:"高",en:"High",si:"උස",h:"たかい",r:"takai"},
{k:"安",en:"Cheap",si:"ලාභ",h:"やすい",r:"yasui"}
];
