let kanjiN4_1 = [

{kanji:"会",kana:"かい",romaji:"kai",meaning:"හමුව / Meeting"},
{kanji:"同",kana:"どう",romaji:"dou",meaning:"එකම / Same"},
{kanji:"事",kana:"こと",romaji:"koto",meaning:"දේ / Thing"},
{kanji:"自",kana:"じ",romaji:"ji",meaning:"ස්වයං / Self"},
{kanji:"社",kana:"しゃ",romaji:"sha",meaning:"සමාගම / Company"},
{kanji:"行",kana:"い/こう",romaji:"i/kou",meaning:"යෑම / Go"},
{kanji:"見",kana:"み/けん",romaji:"mi/ken",meaning:"බැලීම / See"},
{kanji:"月",kana:"つき",romaji:"tsuki",meaning:"චන්ද්‍රයා / Moon"},
{kanji:"思",kana:"おも",romaji:"omo",meaning:"සිතීම / Think"},
{kanji:"時",kana:"とき",romaji:"toki",meaning:"වේලාව / Time"},

{kanji:"間",kana:"ま/かん",romaji:"ma/kan",meaning:"අතර / Interval"},
{kanji:"家",kana:"いえ/か",romaji:"ie/ka",meaning:"ගෙදර / House"},
{kanji:"話",kana:"はなし",romaji:"hanashi",meaning:"කතා / Talk"},
{kanji:"国",kana:"くに",romaji:"kuni",meaning:"රට / Country"},
{kanji:"人",kana:"ひと",romaji:"hito",meaning:"මිනිසා / Person"},
{kanji:"日",kana:"ひ/にち",romaji:"hi/nichi",meaning:"දවස / Day"},
{kanji:"年",kana:"とし",romaji:"toshi",meaning:"වසර / Year"},
{kanji:"出",kana:"で",romaji:"de",meaning:"පිටවීම / Exit"},
{kanji:"入",kana:"はい",romaji:"hai",meaning:"ඇතුල්වීම / Enter"},
{kanji:"学",kana:"がく",romaji:"gaku",meaning:"ඉගෙනීම / Study"},

{kanji:"高",kana:"たか",romaji:"taka",meaning:"උස / High"},
{kanji:"長",kana:"なが",romaji:"naga",meaning:"දිග / Long"},
{kanji:"大",kana:"おお",romaji:"oo",meaning:"විශාල / Big"},
{kanji:"小",kana:"ちい",romaji:"chii",meaning:"කුඩා / Small"},
{kanji:"新",kana:"あたら",romaji:"atarashi",meaning:"අලුත් / New"},
{kanji:"古",kana:"ふる",romaji:"furu",meaning:"පරණ / Old"},
{kanji:"多",kana:"おお",romaji:"oo",meaning:"බොහෝ / Many"},
{kanji:"少",kana:"すく",romaji:"suku",meaning:"අඩු / Few"},
{kanji:"白",kana:"しろ",romaji:"shiro",meaning:"සුදු / White"},
{kanji:"黒",kana:"くろ",romaji:"kuro",meaning:"කළු / Black"},

{kanji:"山",kana:"やま",romaji:"yama",meaning:"කන්ද / Mountain"},
{kanji:"川",kana:"かわ",romaji:"kawa",meaning:"ගඟ / River"},
{kanji:"電",kana:"でん",romaji:"den",meaning:"විදුලිය / Electricity"},
{kanji:"車",kana:"くるま",romaji:"kuruma",meaning:"කාර් / Car"},
{kanji:"駅",kana:"えき",romaji:"eki",meaning:"දුම්රිය ස්ථානය / Station"},
{kanji:"空",kana:"そら",romaji:"sora",meaning:"අහස / Sky"},
{kanji:"雨",kana:"あめ",romaji:"ame",meaning:"වහි / Rain"},
{kanji:"風",kana:"かぜ",romaji:"kaze",meaning:"සුළඟ / Wind"},
{kanji:"魚",kana:"さかな",romaji:"sakana",meaning:"මාළු / Fish"},
{kanji:"肉",kana:"にく",romaji:"niku",meaning:"මස් / Meat"},

{kanji:"食",kana:"た",romaji:"ta",meaning:"කෑම / Eat"},
{kanji:"飲",kana:"の",romaji:"no",meaning:"බීම / Drink"},
{kanji:"聞",kana:"き",romaji:"ki",meaning:"අසීම / Listen"},
{kanji:"書",kana:"か",romaji:"ka",meaning:"ලියන්න / Write"},
{kanji:"読",kana:"よ",romaji:"yo",meaning:"කියවීම / Read"},
{kanji:"買",kana:"か",romaji:"ka",meaning:"මිලදී ගැනීම / Buy"},
{kanji:"売",kana:"う",romaji:"u",meaning:"විකිණීම / Sell"},
{kanji:"住",kana:"す",romaji:"su",meaning:"ජීවත් වීම / Live"},
{kanji:"働",kana:"はたら",romaji:"hataraku",meaning:"වැඩ / Work"},
{kanji:"休",kana:"やす",romaji:"yasu",meaning:"විවේක / Rest"}

];
