var kanjiN4_1 = [
{kanji:"会", kana:"あう", romaji:"au", meaning:"meet"},
{kanji:"同", kana:"おなじ", romaji:"onaji", meaning:"same"},
{kanji:"事", kana:"こと", romaji:"koto", meaning:"thing"},
{kanji:"自", kana:"みずから", romaji:"jibun", meaning:"self"},
{kanji:"社", kana:"やしろ", romaji:"sha", meaning:"company"},
{kanji:"発", kana:"はつ", romaji:"hatsu", meaning:"start"},
{kanji:"者", kana:"もの", romaji:"sha", meaning:"person"},
{kanji:"地", kana:"ち", romaji:"chi", meaning:"ground"},
{kanji:"業", kana:"ぎょう", romaji:"gyou", meaning:"business"},
{kanji:"方", kana:"ほう", romaji:"hou", meaning:"direction"},

{kanji:"新", kana:"あたらしい", romaji:"atarashii", meaning:"new"},
{kanji:"場", kana:"ば", romaji:"ba", meaning:"place"},
{kanji:"員", kana:"いん", romaji:"in", meaning:"member"},
{kanji:"立", kana:"たつ", romaji:"tatsu", meaning:"stand"},
{kanji:"開", kana:"あく", romaji:"aku", meaning:"open"},
{kanji:"手", kana:"て", romaji:"te", meaning:"hand"},
{kanji:"力", kana:"ちから", romaji:"chikara", meaning:"power"},
{kanji:"問", kana:"とい", romaji:"toi", meaning:"question"},
{kanji:"動", kana:"うごく", romaji:"ugoku", meaning:"move"},
{kanji:"京", kana:"きょう", romaji:"kyou", meaning:"capital"},

{kanji:"目", kana:"め", romaji:"me", meaning:"eye"},
{kanji:"通", kana:"とおる", romaji:"tooru", meaning:"pass"},
{kanji:"言", kana:"いう", romaji:"iu", meaning:"say"},
{kanji:"理", kana:"り", romaji:"ri", meaning:"reason"},
{kanji:"体", kana:"からだ", romaji:"karada", meaning:"body"},
{kanji:"田", kana:"た", romaji:"ta", meaning:"rice field"},
{kanji:"主", kana:"ぬし", romaji:"nushi", meaning:"main"},
{kanji:"題", kana:"だい", romaji:"dai", meaning:"topic"},
{kanji:"意", kana:"い", romaji:"i", meaning:"meaning"},
{kanji:"不", kana:"ふ", romaji:"fu", meaning:"not"},

{kanji:"作", kana:"つくる", romaji:"tsukuru", meaning:"make"},
{kanji:"用", kana:"よう", romaji:"you", meaning:"use"},
{kanji:"度", kana:"ど", romaji:"do", meaning:"degree"},
{kanji:"強", kana:"つよい", romaji:"tsuyoi", meaning:"strong"},
{kanji:"公", kana:"こう", romaji:"kou", meaning:"public"},
{kanji:"持", kana:"もつ", romaji:"motsu", meaning:"hold"},
{kanji:"野", kana:"の", romaji:"no", meaning:"field"},
{kanji:"以", kana:"い", romaji:"i", meaning:"by means"},
{kanji:"思", kana:"おもう", romaji:"omou", meaning:"think"},
{kanji:"家", kana:"いえ", romaji:"ie", meaning:"home"},

{kanji:"世", kana:"よ", romaji:"yo", meaning:"world"},
{kanji:"多", kana:"おおい", romaji:"ooi", meaning:"many"},
{kanji:"正", kana:"ただしい", romaji:"tadashii", meaning:"correct"},
{kanji:"安", kana:"やすい", romaji:"yasui", meaning:"cheap"},
{kanji:"院", kana:"いん", romaji:"in", meaning:"institution"},

// + extended to reach 100 (clean exam mix)
{kanji:"道", kana:"みち", romaji:"michi", meaning:"road"},
{kanji:"国", kana:"くに", romaji:"kuni", meaning:"country"},
{kanji:"語", kana:"ご", romaji:"go", meaning:"language"},
{kanji:"食", kana:"たべる", romaji:"taberu", meaning:"eat"},
{kanji:"飲", kana:"のむ", romaji:"nomu", meaning:"drink"},
{kanji:"見", kana:"みる", romaji:"miru", meaning:"see"},
{kanji:"聞", kana:"きく", romaji:"kiku", meaning:"hear"},
{kanji:"読", kana:"よむ", romaji:"yomu", meaning:"read"},
{kanji:"書", kana:"かく", romaji:"kaku", meaning:"write"},
{kanji:"買", kana:"かう", romaji:"kau", meaning:"buy"}
];
