const kanjiN5 = [
{kanji:"日",romaji:"nichi / hi",meaning:"දවස"},
{kanji:"月",romaji:"getsu / tsuki",meaning:"මාසය"},
{kanji:"火",romaji:"hi",meaning:"ගිනි"},
{kanji:"水",romaji:"mizu",meaning:"වතුර"},
{kanji:"木",romaji:"ki",meaning:"ගස"},
{kanji:"金",romaji:"kin / kane",meaning:"සල්ලි"},
{kanji:"土",romaji:"tsuchi",meaning:"පොළොව"},

{kanji:"人",romaji:"hito",meaning:"මිනිසා"},
{kanji:"男",romaji:"otoko",meaning:"පිරිමි"},
{kanji:"女",romaji:"onna",meaning:"කාන්තාව"},
{kanji:"子",romaji:"ko",meaning:"දරුවා"},
{kanji:"父",romaji:"chichi",meaning:"තාත්තා"},
{kanji:"母",romaji:"haha",meaning:"අම්මා"},

{kanji:"目",romaji:"me",meaning:"ඇස"},
{kanji:"耳",romaji:"mimi",meaning:"කන"},
{kanji:"口",romaji:"kuchi",meaning:"කට"},
{kanji:"手",romaji:"te",meaning:"අත"},
{kanji:"足",romaji:"ashi",meaning:"පාදය"},

{kanji:"山",romaji:"yama",meaning:"කන්ද"},
{kanji:"川",romaji:"kawa",meaning:"ගඟ"},
{kanji:"田",romaji:"ta",meaning:"කුඹුර"},
{kanji:"空",romaji:"sora",meaning:"අහස"},
{kanji:"雨",romaji:"ame",meaning:"වැස්ස"},
{kanji:"風",romaji:"kaze",meaning:"සුළඟ"},

{kanji:"上",romaji:"ue",meaning:"ඉහළ"},
{kanji:"下",romaji:"shita",meaning:"පහළ"},
{kanji:"中",romaji:"naka",meaning:"මැද"},
{kanji:"外",romaji:"soto",meaning:"පිටත"},
{kanji:"前",romaji:"mae",meaning:"ඉදිරිය"},
{kanji:"後",romaji:"ato",meaning:"පසුපස"},

{kanji:"一",romaji:"ichi",meaning:"1"},
{kanji:"二",romaji:"ni",meaning:"2"},
{kanji:"三",romaji:"san",meaning:"3"},
{kanji:"四",romaji:"shi",meaning:"4"},
{kanji:"五",romaji:"go",meaning:"5"},
{kanji:"六",romaji:"roku",meaning:"6"},
{kanji:"七",romaji:"shichi",meaning:"7"},
{kanji:"八",romaji:"hachi",meaning:"8"},
{kanji:"九",romaji:"kyu",meaning:"9"},
{kanji:"十",romaji:"ju",meaning:"10"},

{kanji:"学",romaji:"gaku",meaning:"ඉගෙනීම"},
{kanji:"校",romaji:"kou",meaning:"පාසල"},
{kanji:"本",romaji:"hon",meaning:"පොත"},
{kanji:"語",romaji:"go",meaning:"භාෂාව"},
{kanji:"文",romaji:"bun",meaning:"වචන"},

{kanji:"見",romaji:"mi",meaning:"බැලීම"},
{kanji:"聞",romaji:"ki",meaning:"ඇසීම"},
{kanji:"行",romaji:"iku",meaning:"යෑම"},
{kanji:"来",romaji:"ku",meaning:"එනවා"},
{kanji:"出",romaji:"de",meaning:"පිටවීම"},
{kanji:"入",romaji:"hai",meaning:"ඇතුල්වීම"},

{kanji:"高",romaji:"taka",meaning:"ඉහළ"},
{kanji:"安",romaji:"yasu",meaning:"අඩු මිල"},
{kanji:"新",romaji:"shin",meaning:"අලුත්"},
{kanji:"古",romaji:"furu",meaning:"පරණ"},
{kanji:"多",romaji:"oo",meaning:"ගොඩක්"},
{kanji:"少",romaji:"suku",meaning:"අඩු"},

{kanji:"車",romaji:"kuruma",meaning:"කාර්"},
{kanji:"門",romaji:"mon",meaning:"දොරටුව"},
{kanji:"休",romaji:"yasu",meaning:"විවේකය"},
{kanji:"買",romaji:"kai",meaning:"මිලදී"},
{kanji:"売",romaji:"uri",meaning:"විකිණීම"},

{kanji:"食",romaji:"shoku",meaning:"කෑම"},
{kanji:"飲",romaji:"nomu",meaning:"බීම"},
{kanji:"書",romaji:"sho",meaning:"ලියනවා"},
{kanji:"読",romaji:"yomu",meaning:"කියවීම"},
{kanji:"話",romaji:"hanasu",meaning:"කතා"},

{kanji:"町",romaji:"machi",meaning:"නගරය"},
{kanji:"村",romaji:"mura",meaning:"ගම්මානය"},
{kanji:"店",romaji:"mise",meaning:"කඩය"},
{kanji:"駅",romaji:"eki",meaning:"ස්ටේෂන්"},
{kanji:"道",romaji:"michi",meaning:"පාර"}
];

console.log("N5 Kanji loaded:", kanjiN5.length);
